"""Initial migration

Revision ID: 35fb3f7db201
Revises: 
Create Date: 2024-12-14 16:55:18.788307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35fb3f7db201'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_requests', 'requestor',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_data_requests_id'), 'data_requests', ['id'], unique=False)
    op.alter_column('data_sources', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('name', table_name='data_sources')
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.alter_column('disaster_data', 'data_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('disaster_data', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('disaster_data', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('integrated_code', table_name='disaster_data')
    op.create_index(op.f('ix_disaster_data_id'), 'disaster_data', ['id'], unique=False)
    op.drop_column('disaster_data', 'carrier_code')
    op.drop_column('disaster_data', 'integrated_code')
    op.drop_column('disaster_data', 'source_code')
    op.drop_column('disaster_data', 'earthquake_code')
    op.drop_column('disaster_data', 'disaster_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disaster_data', sa.Column('disaster_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=6), nullable=False))
    op.add_column('disaster_data', sa.Column('earthquake_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=26), nullable=False))
    op.add_column('disaster_data', sa.Column('source_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), nullable=False))
    op.add_column('disaster_data', sa.Column('integrated_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=False))
    op.add_column('disaster_data', sa.Column('carrier_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=False))
    op.drop_index(op.f('ix_disaster_data_id'), table_name='disaster_data')
    op.create_index('integrated_code', 'disaster_data', ['integrated_code'], unique=True)
    op.alter_column('disaster_data', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('disaster_data', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('disaster_data', 'data_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.create_index('name', 'data_sources', ['name'], unique=True)
    op.alter_column('data_sources', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_data_requests_id'), table_name='data_requests')
    op.alter_column('data_requests', 'requestor',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
